spring:
  application:
    name: inventory-service  # Service name to be used in Eureka registry

server:
  port: 8081  # Inventory service will run on port 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/