spring:
  application:
    name: orders-service

  cloud:
    config:
      uri: http://localhost:8888  # Config Server URL
      profile: dev  # Active profile (dev, prod, etc.) other- development
      label: master  # Git branch/tag for version control

#http://localhost:8888/orders-service/dev