spring:
  application:
    name: orders-service

  sleuth:
    sampler:
      probability: 1.0  # 100% sampling rate  --0.1

  zipkin:
    base-url: http://localhost:9411  # Zipkin server URL

  #http://localhost:9411/orders/1234