server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true # tells Eureka to reigister the ip address of instance instead of localost

spring:
  application:
    name: my-microservice

